version: '3.8'

networks:
  mynetwork:
    driver: bridge  # 네트워크 드라이버 설정 (bridge는 기본값)

services:
  auth-service:
    build:
      context: ./Backend/Image/auth-service
      dockerfile: Dockerfile
    image: itda-auth:1.0
    container_name: auth-service
    env_file:
      - ./Backend/Image/auth-service/.env
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

  search-service:
    build:
      context: ./Backend/Image/search-service
      dockerfile: Dockerfile
    image: itda-search:1.0
    container_name: search-service
    env_file:
      - ./Backend/Image/search-service/.env
    ports:
      - "3002:3002"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lyrics-service:
    build:
      context: ./Backend/Image/lyrics-service
      dockerfile: Dockerfile
    image: itda-lyrics:1.0
    container_name: lyrics-service
    env_file:
      - ./Backend/Image/lyrics-service/.env
    ports:
      - "3003:3003"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

  translation-service:
    build:
      context: ./Backend/Image/translation-service
      dockerfile: Dockerfile
    image: itda-translation:1.0
    container_name: translation-service
    env_file:
      - ./Backend/Image/translation-service/.env
    ports:
      - "3004:3004"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

  playlist-service:
    build:
      context: ./Backend/Image/playlist-service
      dockerfile: Dockerfile
    image: itda-playlist:1.0
    container_name: playlist-service
    env_file:
      - ./Backend/Image/playlist-service/.env
    ports:
      - "3005:3005"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: ./Frontend/bravo-front
      dockerfile: Dockerfile
    image: itda-ui:1.0
    container_name: bravo-front
    env_file:
      - ./Frontend/bravo-front/.env
    ports:
      - "5174:5174"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

