# Image/lyrics-service/docker-compose.yaml

version: '3.8'

services:
  app:
    image: lyrics-service:test
    restart: always
    env_file:
      - .env
    environment:
      # Lyrics Service 전용 환경 변수
      PORT: "3003"
      MONGO_URI: "mongodb://192.168.2.137:27017/itda"
      MUSIXMATCH_API_KEY: "52cc61f2ffmshb86927d07d2d28dp1fc423jsn79e0002666b3"
      MUSIXMATCH_API_HOST: "musixmatch-lyrics-songs.p.rapidapi.com"
      LRCLIB_API_BASE: "https://lrclib.net"
    ports:
      - "3003:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

