# Image/translation-service/docker-compose.yaml

version: '3.8'

services:
  app:
    image: translation-service:test
    restart: always
    env_file:
      - .env
    environment:
      # Translation Service 전용 환경 변수
      PORT: "3004"
      MONGO_URI: "mongodb://192.168.2.137:27017/itda"
      AWS_ACCESS_KEY_ID: "AKIAZRBSKGNTYVRA2PEA"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_REGION: "us-east-1"
      INFERENCE_PROFILE_ARN: "arn:aws:bedrock:us-east-1:655088038759:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0"
    ports:
      - "3004:3004"
    extra_hosts:
      - "host.docker.internal:host-gateway"

