version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable  # 또는 :latest, :<버전> 등 사용 가능
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Images
          command: docker-compose -f docker-compose.yaml build
      - run:
          name: Start Services
          command: docker-compose -f docker-compose.yaml up -d
      - run:
          name: Run Tests
          command: docker-compose -f docker-compose.yaml exec auth-service npm test
      - run:
          name: Stop Services
          command: docker-compose -f docker-compose.yaml down

workflows:
  version: 2
  build_test_workflow:
    jobs:
      - build_and_test

