version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # 자체 서명된 SSL 인증서 설치
      - run:
          name: Install Harbor SSL Certificate
          command: |
            # 인증서 파일을 다운로드하거나 CircleCI 환경에 업로드된 인증서 파일을 사용
            mkdir -p /usr/local/share/ca-certificates/extra
            cp ./path/to/your/ca.crt /usr/local/share/ca-certificates/extra/harbor.crt
            update-ca-certificates

      # Docker Compose로 이미지 빌드
      - run:
          name: Build Docker Images
          command: docker-compose -f docker-compose.yaml build

      # Docker 이미지 태깅
      - run:
          name: Tag Docker Images for Harbor
          command: |
            docker tag itda-auth:1.0 $HARBOR_URL/$HARBOR_PROJECT/itda-auth:1.0
            docker tag itda-search:1.0 $HARBOR_URL/$HARBOR_PROJECT/itda-search:1.0
            docker tag itda-lyrics:1.0 $HARBOR_URL/$HARBOR_PROJECT/itda-lyrics:1.0

      # Harbor에 로그인
      - run:
          name: Log in to Harbor
          command: echo "$HARBOR_PASSWORD" | docker login $HARBOR_URL --username "$HARBOR_USERNAME" --password-stdin

      # Harbor로 Docker 이미지 푸시
      - run:
          name: Push Docker Images to Harbor
          command: |
            docker push $HARBOR_URL/$HARBOR_PROJECT/itda-auth:1.0
            docker push $HARBOR_URL/$HARBOR_PROJECT/itda-search:1.0
            docker push $HARBOR_URL/$HARBOR_PROJECT/itda-lyrics:1.0

      # 프론트엔드와 백엔드 서비스 실행
      - run:
          name: Start Services
          command: |
            docker-compose -f docker-compose.yaml up -d

      # 서비스 종료
      - run:
          name: Stop Services
          command: docker-compose -f docker-compose.yaml down

workflows:
  version: 2
  build_test_workflow:
    jobs:
      - build_and_test

