# Image/auth-service/docker-compose.yaml


version: '3.8'

services:
  app:
    image: auth-service:test
    restart: always
    env_file:
      - .env
    environment:
      # Auth Service 전용 환경 변수
      PORT: "3001"
      GOOGLE_CLIENT_ID: "726485372630-lfnjv8ojeud68fgpus2o67fd60f4olkq.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      GOOGLE_REDIRECT_URI: "http://localhost:3001/api/google/google-callback"
      FRONTEND_URL: "http://localhost:5174"
      JWT_SECRET: "5F3GEsB0LqLR+Akqn7HspsHI3Ae5x+CmYq4vrMABQn8lqfqyVkilVIV9dinKy4zyJl/SsCk1FMBHzwpJs3ip6w=="
      MONGO_URI: "mongodb://192.168.2.137:27017/itda"
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

