# Image/search-service/docker-compose.yaml

version: '3.8'

services:
  app:
    image: search-service:test
    restart: always
    env_file:
      - .env
    environment:
      # Search Service 전용 환경 변수
      PORT: "3002"
      SPOTIFY_CLIENT_ID: "0ff07a899a8845c88e23c98afbce43ab"
      SPOTIFY_CLIENT_SECRET: "55f10044db254b02aa33dee00a4883e3"
      YOUTUBE_API_KEYS: "AIzaSyAybmmX582Mt6HJa8VGTPRHABl8vHh_euk,AIzaSyAwcUsgAODlJAndOnlnYKqbGGtnjS_L61E,AIzaSyDjf1hY6e6IOYz92SErP4QWWD_dLWU6Mg,AIzaSyB13uyTh3SChfAB7RNjQ8HBwe61wpqU0,AIzaSyBGPRpwt-kaZV4THET0AYyxo8w0AZ7DQ9E,AIzaSyBIq-Sj7ENDnXWI-CJ049AYLOq_u_9lc7U,AIzaSyDXTe20_t-fgvQgC9WfOonxht7LyWdsrP0,AIzaSyD4eJxcVyM9ufvwDqQyWcwMtkwnfpaFYes,AIzaSyC-9G1S6udZOe85pU-d6HhVBQthI0M78TE,AIzaSyAo8nju1RfmVv_rkTn54siCu9-9TliONbg,AIzaSyCnO9sZGAii8wP5qgWmLfTBszjSuRgTPoE"
      MONGO_URI: "mongodb://192.168.2.137:27017/itda"
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"

