#frontend .docker-compose.yaml

version: '3.8'

networks:
  mynetwork: # ✅ 모든 서비스가 같은 네트워크를 사용하도록 설정
    external: true # ✅ 외부 네트워크 사용

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bravo-front:test
    container_name: bravo-front
    env_file:
      - .env
    ports:
      - "5174:5174"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
